MODEL_NAME = "qwen/qwen-2.5-7b-instruct"
POLICY_VERSION = "EC_POLICY_V1"
RECONCILIATION_TOLERANCE = "0.10"
MAX_REPAIR_ATTEMPTS = 2
ROOT_CAUSES = {
    "SELLER_HANDOFF_AFTER_LIMIT",
    "CARRIER_DELIVERED_AFTER_ESTIMATE",
    "ORDER_CANCELED_AFTER_PAYMENT",
    "ORDER_UNAVAILABLE_AFTER_PAYMENT",
    "MULTIPLE_PAYMENTS_RECONCILED",
    "DELIVERY_WITHIN_ESTIMATE",
}
