CREATE TABLE IF NOT EXISTS customers (customer_id TEXT PRIMARY KEY, customer_unique_id TEXT NOT NULL, customer_zip_code_prefix INTEGER, customer_city TEXT, customer_state TEXT);
CREATE TABLE IF NOT EXISTS orders (order_id TEXT PRIMARY KEY, customer_id TEXT, order_status TEXT NOT NULL, order_purchase_timestamp TIMESTAMP, order_approved_at TIMESTAMP, order_delivered_carrier_date TIMESTAMP, order_delivered_customer_date TIMESTAMP, order_estimated_delivery_date TIMESTAMP);
CREATE TABLE IF NOT EXISTS order_items (order_id TEXT NOT NULL REFERENCES orders(order_id), order_item_id INTEGER NOT NULL, product_id TEXT, seller_id TEXT, shipping_limit_date TIMESTAMP, price NUMERIC(12,2), freight_value NUMERIC(12,2), PRIMARY KEY(order_id, order_item_id));
CREATE TABLE IF NOT EXISTS order_payments (order_id TEXT NOT NULL REFERENCES orders(order_id), payment_sequential INTEGER NOT NULL, payment_type TEXT, payment_installments INTEGER, payment_value NUMERIC(12,2), PRIMARY KEY(order_id, payment_sequential));
CREATE TABLE IF NOT EXISTS sellers (seller_id TEXT PRIMARY KEY, seller_zip_code_prefix INTEGER, seller_city TEXT, seller_state TEXT);
CREATE TABLE IF NOT EXISTS products (product_id TEXT PRIMARY KEY, product_category_name TEXT);
CREATE TABLE IF NOT EXISTS order_reviews (review_id TEXT PRIMARY KEY, order_id TEXT, review_score INTEGER, review_comment_title TEXT, review_comment_message TEXT, review_creation_date TIMESTAMP, review_answer_timestamp TIMESTAMP);
CREATE TABLE IF NOT EXISTS geolocation (geolocation_zip_code_prefix INTEGER, geolocation_lat NUMERIC, geolocation_lng NUMERIC, geolocation_city TEXT, geolocation_state TEXT);
CREATE TABLE IF NOT EXISTS cases (case_id TEXT PRIMARY KEY, input_json JSONB NOT NULL, policy_version TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS runs (run_id TEXT PRIMARY KEY, case_id TEXT REFERENCES cases(case_id), status TEXT NOT NULL, started_at TIMESTAMP NOT NULL DEFAULT NOW(), finished_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS agent_handoffs (id BIGSERIAL PRIMARY KEY, run_id TEXT REFERENCES runs(run_id), node_name TEXT NOT NULL, payload JSONB NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS case_results (case_id TEXT PRIMARY KEY, run_id TEXT, output_json JSONB NOT NULL, verified BOOLEAN NOT NULL);
CREATE TABLE IF NOT EXISTS trace_references (case_id TEXT PRIMARY KEY, run_id TEXT, trace_id TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_order_items_seller ON order_items(seller_id);
CREATE INDEX IF NOT EXISTS idx_order_payments_order ON order_payments(order_id);
