CREATE SCHEMA IF NOT EXISTS olist;

CREATE TABLE IF NOT EXISTS olist.customers (
    customer_id VARCHAR(64) PRIMARY KEY,
    customer_unique_id VARCHAR(64) NOT NULL,
    customer_zip_code_prefix INTEGER NOT NULL,
    customer_city VARCHAR(128) NOT NULL,
    customer_state VARCHAR(2) NOT NULL
);

CREATE TABLE IF NOT EXISTS olist.orders (
    order_id VARCHAR(64) PRIMARY KEY,
    customer_id VARCHAR(64) NOT NULL,
    order_status VARCHAR(32) NOT NULL,
    order_purchase_timestamp TIMESTAMP NOT NULL,
    order_approved_at TIMESTAMP NULL,
    order_delivered_carrier_date TIMESTAMP NULL,
    order_delivered_customer_date TIMESTAMP NULL,
    order_estimated_delivery_date TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS olist.order_items (
    order_id VARCHAR(64) NOT NULL,
    order_item_id INTEGER NOT NULL,
    product_id VARCHAR(64) NOT NULL,
    seller_id VARCHAR(64) NOT NULL,
    shipping_limit_date TIMESTAMP NOT NULL,
    price NUMERIC(12, 2) NOT NULL,
    freight_value NUMERIC(12, 2) NOT NULL,
    PRIMARY KEY (order_id, order_item_id)
);

CREATE TABLE IF NOT EXISTS olist.order_payments (
    order_id VARCHAR(64) NOT NULL,
    payment_sequential INTEGER NOT NULL,
    payment_type VARCHAR(32) NOT NULL,
    payment_installments INTEGER NOT NULL,
    payment_value NUMERIC(12, 2) NOT NULL,
    PRIMARY KEY (order_id, payment_sequential)
);

CREATE TABLE IF NOT EXISTS olist.order_reviews (
    review_row_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id VARCHAR(64) NOT NULL,
    order_id VARCHAR(64) NOT NULL,
    review_score INTEGER NOT NULL,
    review_comment_title TEXT NULL,
    review_comment_message TEXT NULL,
    review_creation_date TIMESTAMP NOT NULL,
    review_answer_timestamp TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS olist.products (
    product_id VARCHAR(64) PRIMARY KEY,
    product_category_name VARCHAR(128) NULL,
    product_name_lenght INTEGER NULL,
    product_description_lenght INTEGER NULL,
    product_photos_qty INTEGER NULL,
    product_weight_g INTEGER NULL,
    product_length_cm INTEGER NULL,
    product_height_cm INTEGER NULL,
    product_width_cm INTEGER NULL
);

CREATE TABLE IF NOT EXISTS olist.sellers (
    seller_id VARCHAR(64) PRIMARY KEY,
    seller_zip_code_prefix INTEGER NOT NULL,
    seller_city VARCHAR(128) NOT NULL,
    seller_state VARCHAR(2) NOT NULL
);

CREATE TABLE IF NOT EXISTS olist.category_translation (
    product_category_name VARCHAR(128) PRIMARY KEY,
    product_category_name_english VARCHAR(128) NOT NULL
);

CREATE TABLE IF NOT EXISTS olist.geolocation (
    geolocation_row_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    geolocation_zip_code_prefix INTEGER NOT NULL,
    geolocation_lat NUMERIC(12, 9) NOT NULL,
    geolocation_lng NUMERIC(12, 9) NOT NULL,
    geolocation_city VARCHAR(128) NOT NULL,
    geolocation_state VARCHAR(2) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_orders_customer_id ON olist.orders(customer_id);
CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON olist.order_items(order_id);
CREATE INDEX IF NOT EXISTS idx_order_items_seller_id ON olist.order_items(seller_id);
CREATE INDEX IF NOT EXISTS idx_order_items_product_id ON olist.order_items(product_id);
CREATE INDEX IF NOT EXISTS idx_order_items_shipping_limit ON olist.order_items(shipping_limit_date);
CREATE INDEX IF NOT EXISTS idx_order_payments_order_id ON olist.order_payments(order_id);
CREATE INDEX IF NOT EXISTS idx_order_reviews_order_id ON olist.order_reviews(order_id);
CREATE INDEX IF NOT EXISTS idx_geolocation_zip ON olist.geolocation(geolocation_zip_code_prefix);

